version: "3.9"
services:
  api:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: ["python", "run.py"]
  worker:
    build: .
    env_file: .env
    depends_on:
      - redis
    command: ["celery", "-A", "tasks.celery", "worker", "--loglevel=info"]
  redis:
    image: redis:7-alpine
